/**
 * TruthShield Provenance Detector
 * Analyzes file signatures, metadata, filenames, and contents
 * to determine the origin (from where) and creator (from what device/AI model)
 * of images and videos.
 */
class ProvenanceDetector {
  constructor() {
    // Known social media filename regex patterns
    this.platformPatterns = [
      { name: 'WhatsApp', regex: /IMG-\d{8}-WA\d{4}/i, desc: 'Shared via WhatsApp. Metadata typically stripped during compression.' },
      { name: 'WhatsApp Video', regex: /VID-\d{8}-WA\d{4}/i, desc: 'Shared via WhatsApp Video. Metadata and audio tracks highly compressed.' },
      { name: 'Telegram', regex: /telegram-cloud-photo/i, desc: 'Downloaded from Telegram cloud storage.' },
      { name: 'Facebook', regex: /fb_img_\d+/i, desc: 'Saved from Facebook app. EXIF metadata stripped.' },
      { name: 'Instagram', regex: /instagram/i, desc: 'Downloaded or saved from Instagram. Profile/EXIF data stripped.' },
      { name: 'Twitter/X', regex: /[a-z0-9_-]{15}\.(jpg|png|jpeg)/i, desc: 'Common filename structure for media downloaded from Twitter/X.' },
      { name: 'Reddit', regex: /reddit/i, desc: 'Saved from Reddit. May contain watermarked attribution footer.' }
    ];

    // Known AI Image Generators signature keywords
    this.aiSignatures = [
      { name: 'Midjourney', keywords: ['midjourney', 'mjv', 'mj_run', 'creative commons'], software: ['midjourney'] },
      { name: 'DALL-E 3', keywords: ['dall-e', 'dalle', 'openai', 'generation-id'], software: ['dall-e', 'openai'] },
      { name: 'Stable Diffusion', keywords: ['stable-diffusion', 'stable diffusion', 'automatic1111', 'compvis', 'sdxl', 'euler a', 'diffusion'], software: ['stable diffusion', 'sdxl', 'automatic1111'] },
      { name: 'Adobe Firefly', keywords: ['firefly', 'adobe firefly', 'content credentials', 'c2pa'], software: ['adobe firefly', 'photoshop firefly'] },
      { name: 'Canva AI', keywords: ['canva', 'canva design'], software: ['canva'] }
    ];

    // Known AI Video Generators
    this.aiVideoSignatures = [
      { name: 'Sora (OpenAI)', keywords: ['sora', 'openai sora', 'text-to-video sora'] },
      { name: 'Runway Gen-2', keywords: ['runway', 'runwayml', 'gen2', 'gen-2'] },
      { name: 'Pika Labs', keywords: ['pika', 'pikalabs', 'pika-art'] },
      { name: 'Luma Dream Machine', keywords: ['luma', 'lumalabs', 'dream machine'] },
      { name: 'HeyGen (Avatar)', keywords: ['heygen', 'heygen avatar', 'synthesia'] }
    ];
  }

  /**
   * Main analysis method for Images
   * @param {File} file - The uploaded image file
   * @param {HTMLImageElement} img - Loaded image element
   * @param {Object} elaResult - Results from Error Level Analysis (optional)
   * @param {Object} ganResult - Results from GAN detection (optional)
   * @returns {Promise<Object>} Provenance result
   */
  async analyzeImage(file, img, elaResult = null, ganResult = null) {
    const name = file.name;
    const arrayBuffer = await file.arrayBuffer();
    const view = new DataView(arrayBuffer);
    
    // 1. Detect platform/app origin from file name
    const platformMatch = this.detectPlatformFromName(name);
    
    // 2. Extract advanced EXIF tags (including GPS & detailed Software/Hardware Info)
    const exif = this.parseDetailedExif(view);
    
    // 3. Detect if AI Generated (Metadata + Filename + Visual checks)
    const aiDetection = this.detectAIGeneration(file, exif, img);
    
    // 4. Determine Capture Device (Smartphone, DSLR, etc.)
    const device = this.detectCaptureDevice(exif, name);

    // 5. Generate Reverse Search Queries & Links
    const reverseSearch = this.generateReverseSearchLinks(file, name);

    // 6. Calculate breakdown scores: AI Creation %, Manual Edit %, Original Capture %
    const scores = this.calculateImageScores(file, exif, img, elaResult, ganResult, aiDetection, device, platformMatch);

    // 7. Summary Verdict
    let originSummary = '';
    let originLocation = 'Unknown';
    if (exif && exif.gps && exif.gps.latitude) {
      originLocation = `${exif.gps.latitude.toFixed(5)}, ${exif.gps.longitude.toFixed(5)}`;
      if (exif.gps.city) originLocation += ` (${exif.gps.city})`;
    }

    if (scores.ai > scores.edit && scores.ai > scores.raw) {
      originSummary = `Synthetically generated by AI (${aiDetection.generator || 'Generative Engine'})`;
    } else if (scores.edit > scores.raw) {
      originSummary = `Manually edited or tampered media (Inferred editing trail)`;
    } else if (device.deviceClass === 'smartphone') {
      originSummary = `Original capture shot on smartphone (${device.model})`;
    } else if (device.deviceClass === 'camera') {
      originSummary = `Original capture taken with professional camera (${device.model})`;
    } else if (platformMatch) {
      originSummary = `Original capture distributed via ${platformMatch.name}`;
    } else {
      originSummary = `Generic capture, no modifications detected`;
    }

    return {
      originSummary,
      location: originLocation,
      gps: exif ? exif.gps : null,
      aiDetection,
      device,
      platform: platformMatch,
      exif,
      reverseSearch,
      scores
    };
  }

  /**
   * Main analysis method for Videos
   * @param {File} file - The uploaded video file
   * @param {Object} consistency - Temporal frame consistency scores (optional)
   * @returns {Promise<Object>} Provenance result
   */
  async analyzeVideo(file, consistency = null) {
    const name = file.name;
    const platformMatch = this.detectPlatformFromName(name);
    
    // Basic video metadata based on file structure/name
    let isAIGenerated = false;
    let aiGenerator = 'Unknown';
    let confidence = 0;
    
    const lowerName = name.toLowerCase();
    for (const sig of this.aiVideoSignatures) {
      for (const kw of sig.keywords) {
        if (lowerName.includes(kw)) {
          isAIGenerated = true;
          aiGenerator = sig.name;
          confidence = 90;
          break;
        }
      }
    }

    // Capture device classification for video
    let deviceModel = 'Unknown';
    let deviceClass = 'Unknown';
    if (lowerName.includes('iphone') || lowerName.includes('apple')) {
      deviceModel = 'Apple iPhone';
      deviceClass = 'smartphone';
    } else if (lowerName.includes('samsung') || lowerName.includes('galaxy')) {
      deviceModel = 'Samsung Galaxy';
      deviceClass = 'smartphone';
    }

    // Screen recording check
    const isScreenRecording = lowerName.includes('screen') || lowerName.includes('recording') || lowerName.includes('screenshot');

    // Calculate video scores
    const scores = this.calculateVideoScores(name, isAIGenerated, isScreenRecording, consistency, platformMatch);

    let originSummary = '';
    if (scores.ai > scores.edit && scores.ai > scores.raw) {
      originSummary = `Synthetically generated video (${aiGenerator || 'Gen-AI'})`;
    } else if (scores.edit > scores.raw) {
      originSummary = isScreenRecording ? `Screen recording / Manual composite capture` : `Manually edited/tampered video file`;
    } else if (platformMatch) {
      originSummary = `Video capture distributed via ${platformMatch.name}`;
    } else {
      originSummary = `Original video recording (No alterations detected)`;
    }

    return {
      originSummary,
      aiDetection: {
        isAI: isAIGenerated,
        generator: aiGenerator,
        confidence
      },
      device: {
        model: deviceModel,
        deviceClass: deviceClass,
        isScreenRecording
      },
      platform: platformMatch,
      reverseSearch: this.generateVideoSearchLinks(file, name),
      scores
    };
  }

  /**
   * Helper to detect social platform from filename
   */
  detectPlatformFromName(name) {
    for (const p of this.platformPatterns) {
      if (p.regex.test(name)) {
        return { name: p.name, description: p.desc };
      }
    }
    return null;
  }

  /**
   * Detailed heuristics classifier for Images (AI creation vs Manual edit vs Original capture)
   */
  calculateImageScores(file, exif, img, elaResult, ganResult, aiDetection, device, platformMatch) {
    let ai = 0;
    let edit = 0;
    let raw = 0;

    const lowerName = file.name.toLowerCase();

    // 1. Evaluate AI Indicators
    if (aiDetection.isAI) {
      ai += aiDetection.confidence;
    }
    
    // Visual indicators for AI (square canvas with no EXIF tags)
    if (img && img.width === img.height && !exif) {
      const commonSizes = [256, 512, 1024, 1536, 2048];
      if (commonSizes.includes(img.width)) {
        ai += 35;
      }
    }
    if (ganResult && ganResult.authenticityScore < 40) {
      ai += 40;
    }

    // 2. Evaluate Manual Editing Indicators
    if (exif && exif.software) {
      const sw = exif.software.toLowerCase();
      const editingTools = ['photoshop', 'gimp', 'paint.net', 'lightroom', 'pixlr', 'canva', 'illustrator', 'acme'];
      if (editingTools.some(tool => sw.includes(tool))) {
        edit += 80;
      }
    }

    // If ELA shows edits (suspicion level)
    if (elaResult && elaResult.suspicionLevel > 15) {
      edit += elaResult.suspicionLevel * 0.9;
    }

    // Screen recording / Screenshot filename indicators
    if (lowerName.includes('screenshot') || lowerName.includes('screen') || lowerName.includes('capture')) {
      edit += 45;
    }

    // 3. Evaluate Original Capture Indicators
    if (exif && (exif.make || exif.model) && !exif.software) {
      raw += 85;
    } else if (exif && exif.gps) {
      raw += 75;
    }

    // If it has standard camera filename but no EXIF
    if (lowerName.startsWith('img_') || lowerName.startsWith('dsc_')) {
      raw += 40;
    }

    // Default base scores if no metrics exist
    if (ai === 0 && edit === 0 && raw === 0) {
      if (platformMatch) {
        // WhatsApp / FB compress and strip EXIF
        raw = 65;
        edit = 20;
        ai = 15;
      } else {
        raw = 50;
        edit = 30;
        ai = 20;
      }
    } else {
      // Normalize values to sum to 100%
      const total = ai + edit + raw;
      ai = Math.round((ai / total) * 100);
      edit = Math.round((edit / total) * 100);
      raw = 100 - (ai + edit); // Ensure they total exactly 100
    }

    return { ai, edit, raw };
  }

  /**
   * Detailed heuristics classifier for Videos
   */
  calculateVideoScores(name, isAIGenerated, isScreenRecording, consistency, platformMatch) {
    let ai = 0;
    let edit = 0;
    let raw = 0;

    const lowerName = name.toLowerCase();

    if (isAIGenerated) {
      ai += 90;
    }

    if (isScreenRecording) {
      edit += 85;
    }

    if (consistency && consistency.score < 60) {
      edit += (100 - consistency.score) * 0.75;
    }

    if (lowerName.includes('edit') || lowerName.includes('composite') || lowerName.includes('cut')) {
      edit += 40;
    }

    if (lowerName.startsWith('vid_') || lowerName.includes('cam')) {
      raw += 50;
    }

    // Default base scores
    if (ai === 0 && edit === 0 && raw === 0) {
      if (platformMatch) {
        raw = 70;
        edit = 20;
        ai = 10;
      } else {
        raw = 60;
        edit = 25;
        ai = 15;
      }
    } else {
      const total = ai + edit + raw;
      ai = Math.round((ai / total) * 100);
      edit = Math.round((edit / total) * 100);
      raw = 100 - (ai + edit);
    }

    return { ai, edit, raw };
  }

  /**
   * Advanced EXIF parsing to fetch Camera, GPS, Software, and extra tags
   */
  parseDetailedExif(view) {
    try {
      if (view.getUint16(0) !== 0xFFD8) return null; // Not a JPEG

      const exifResult = {
        make: null,
        model: null,
        software: null,
        dateTime: null,
        lens: null,
        gps: null
      };

      let offset = 2;
      while (offset < view.byteLength - 4) {
        const marker = view.getUint16(offset);
        if (marker === 0xFFE1) {
          // APP1 segment
          const length = view.getUint16(offset + 2);
          if (view.getUint32(offset + 4) === 0x45786966) { // "Exif"
            this.parseExifStructure(view, offset + 10, exifResult);
            break;
          }
        }
        if ((marker & 0xFF00) !== 0xFF00) break;
        offset += 2 + view.getUint16(offset + 2);
      }

      return exifResult.make || exifResult.model || exifResult.software || exifResult.gps ? exifResult : null;
    } catch (e) {
      console.warn("Exif parser error:", e);
      return null;
    }
  }

  parseExifStructure(view, tiffOffset, out) {
    try {
      const bigEndian = view.getUint16(tiffOffset) === 0x4D4D;
      const getU16 = (o) => view.getUint16(o, !bigEndian);
      const getU32 = (o) => view.getUint32(o, !bigEndian);

      const firstIFDOffset = tiffOffset + getU32(tiffOffset + 4);
      this.parseIFD(view, tiffOffset, firstIFDOffset, bigEndian, out);
    } catch (e) {}
  }

  parseIFD(view, tiffOffset, ifdOffset, bigEndian, out, isGps = false) {
    const getU16 = (o) => view.getUint16(o, !bigEndian);
    const getU32 = (o) => view.getUint32(o, !bigEndian);
    const getRational = (o) => {
      const num = getU32(o);
      const den = getU32(o + 4);
      return den === 0 ? 0 : num / den;
    };

    if (ifdOffset + 2 > view.byteLength) return;
    const numEntries = getU16(ifdOffset);

    // Standard Tag IDs
    const tagMap = {
      0x010F: 'make',
      0x0110: 'model',
      0x0131: 'software',
      0x0132: 'dateTime',
      0xA434: 'lens',
      0x8825: 'gpsOffset' // Offset to GPS Info SubIFD
    };

    // GPS Tag IDs (when isGps is true)
    const gpsMap = {
      0x0001: 'latRef',
      0x0002: 'lat',
      0x0003: 'lonRef',
      0x0004: 'lon'
    };

    const gpsData = out.gps || { latitude: null, longitude: null, city: null };

    for (let i = 0; i < numEntries; i++) {
      const entryOffset = ifdOffset + 2 + i * 12;
      if (entryOffset + 12 > view.byteLength) break;

      const tag = getU16(entryOffset);
      const type = getU16(entryOffset + 2);
      const count = getU32(entryOffset + 4);
      const valueOffset = entryOffset + 8;

      if (!isGps) {
        if (tagMap[tag]) {
          const tagName = tagMap[tag];
          if (tagName === 'gpsOffset') {
            const subOffset = tiffOffset + getU32(valueOffset);
            this.parseIFD(view, tiffOffset, subOffset, bigEndian, out, true);
          } else {
            const str = this.readStringValue(view, tiffOffset, type, count, valueOffset);
            if (str) out[tagName] = str;
          }
        }
      } else {
        if (gpsMap[tag]) {
          const field = gpsMap[tag];
          if (field === 'latRef' || field === 'lonRef') {
            gpsData[field] = String.fromCharCode(view.getUint8(valueOffset));
          } else if (field === 'lat' || field === 'lon') {
            // Read 3 rationals (deg, min, sec)
            const offset = tiffOffset + getU32(valueOffset);
            const deg = getRational(offset);
            const min = getRational(offset + 8);
            const sec = getRational(offset + 16);
            gpsData[field + 'Val'] = deg + min / 60 + sec / 3600;
          }
        }
      }
    }

    // Calculate final Lat/Lon if GPS data is present
    if (isGps && gpsData.latVal && gpsData.lonVal) {
      let lat = gpsData.latVal;
      let lon = gpsData.lonVal;
      if (gpsData.latRef === 'S') lat = -lat;
      if (gpsData.lonRef === 'W') lon = -lon;
      
      gpsData.latitude = lat;
      gpsData.longitude = lon;
      gpsData.city = this.mockReverseGeocode(lat, lon);
      out.gps = gpsData;
    }
  }

  readStringValue(view, tiffOffset, type, count, valueOffset) {
    try {
      if (type === 2 && count < 300) { // ASCII
        const getU32 = (o) => view.getUint32(o);
        const actualOffset = count > 4 ? tiffOffset + view.getUint32(valueOffset) : valueOffset;
        let str = '';
        for (let j = 0; j < count - 1 && actualOffset + j < view.byteLength; j++) {
          str += String.fromCharCode(view.getUint8(actualOffset + j));
        }
        return str.trim();
      }
    } catch(e) {}
    return null;
  }

  mockReverseGeocode(lat, lon) {
    const testSpots = [
      { lat: 23.0225, lon: 72.5714, name: 'Ahmedabad, India (Police Headquarters area)' },
      { lat: 37.7749, lon: -122.4194, name: 'San Francisco, USA' },
      { lat: 40.7128, lon: -74.0060, name: 'New York, USA' },
      { lat: 51.5074, lon: -0.1278, name: 'London, UK' },
      { lat: 35.6762, lon: 139.6503, name: 'Tokyo, Japan' },
      { lat: 21.1702, lon: 72.8311, name: 'Surat, India' },
      { lat: 18.9750, lon: 72.8258, name: 'Mumbai, India' }
    ];

    for (const spot of testSpots) {
      const dist = Math.sqrt(Math.pow(lat - spot.lat, 2) + Math.pow(lon - spot.lon, 2));
      if (dist < 0.1) return spot.name;
    }

    return `Coordinates: ${lat.toFixed(4)}, ${lon.toFixed(4)}`;
  }

  /**
   * Detection logic to identify AI generated media
   */
  detectAIGeneration(file, exif, img) {
    let isAI = false;
    let generator = 'Unknown';
    let confidence = 0;
    const lowerName = file.name.toLowerCase();

    // 1. Check EXIF Software tag
    if (exif && exif.software) {
      const sw = exif.software.toLowerCase();
      for (const sig of this.aiSignatures) {
        if (sig.software.some(s => sw.includes(s))) {
          isAI = true;
          generator = sig.name;
          confidence = 95;
          break;
        }
      }
    }

    // 2. Check filename/keywords if not found in software tag
    if (!isAI) {
      for (const sig of this.aiSignatures) {
        for (const kw of sig.keywords) {
          if (lowerName.includes(kw)) {
            isAI = true;
            generator = sig.name;
            confidence = 80;
            break;
          }
        }
        if (isAI) break;
      }
    }

    // 3. Visual/Statistical cues
    if (!isAI && img) {
      const isSquare = img.width === img.height;
      const commonSizes = [256, 512, 1024, 1536, 2048];
      const isCommonAISize = commonSizes.includes(img.width) && isSquare;

      if (isCommonAISize && !exif) {
        isAI = true;
        generator = 'Generative AI (Likely Midjourney or SDXL)';
        confidence = 65;
      }
    }

    return { isAI, generator, confidence };
  }

  /**
   * Device model/class detection
   */
  detectCaptureDevice(exif, filename) {
    if (exif && (exif.make || exif.model)) {
      const model = exif.model || 'Unknown Model';
      const make = exif.make || 'Unknown Make';
      const fullName = `${make} ${model}`;

      let deviceClass = 'camera';
      const lowerFullName = fullName.toLowerCase();
      if (lowerFullName.includes('iphone') || lowerFullName.includes('apple') || 
          lowerFullName.includes('samsung') || lowerFullName.includes('pixel') || 
          lowerFullName.includes('oneplus') || lowerFullName.includes('xiaomi')) {
        deviceClass = 'smartphone';
      }

      return {
        model: fullName,
        deviceClass,
        isEdited: !!exif.software
      };
    }

    // Filename pattern backup
    const lowerName = filename.toLowerCase();
    if (lowerName.startsWith('img_') || lowerName.startsWith('dsc_') || lowerName.startsWith('cimg')) {
      return {
        model: 'Digital Camera (Inferred from filename)',
        deviceClass: 'camera',
        isEdited: false
      };
    }

    return {
      model: 'Unknown Capture Device',
      deviceClass: 'unknown',
      isEdited: false
    };
  }

  /**
   * Generates clickable reverse search links
   */
  generateReverseSearchLinks(file, filename) {
    return [
      { name: 'Filename Search (Google)', url: `https://www.google.com/search?q=${encodeURIComponent(filename)}`, icon: 'fab fa-google', desc: `Search for instances of filename "${filename}" online` },
      { name: 'Google Lens', url: 'https://lens.google.com/', icon: 'fab fa-google', desc: 'Drag-and-drop the file to search origin' },
      { name: 'TinEye Reverse Search', url: 'https://tineye.com/', icon: 'fas fa-magnifying-glass', desc: 'Finds exact duplicate images online' },
      { name: 'Yandex Visual Search', url: 'https://yandex.com/images/search', icon: 'fab fa-yandex', desc: 'Highly effective for face matches and objects' }
    ];
  }

  generateVideoSearchLinks(file, filename) {
    return [
      { name: 'Filename Search (Google)', url: `https://www.google.com/search?q=${encodeURIComponent(filename)}`, icon: 'fab fa-google', desc: `Search for instances of filename "${filename}" online` },
      { name: 'Google Lens (Frame Search)', url: 'https://lens.google.com/', icon: 'fab fa-google', desc: 'Analyse key frames using visual search' },
      { name: 'InVID Verification Plugin', url: 'https://www.invid-project.eu/', icon: 'fas fa-shield-halved', desc: 'Professional tool for video verification and metadata forensics' }
    ];
  }
}

// Export globally
window.ProvenanceDetector = new ProvenanceDetector();
